### ISSUE TITLE
Angular 2.0.0-beta.15 wants zone.js 0.6.10

### ISSUE THREAD

**Issue by dlabaj** [primefaces/primeng-quickstart#3]
Realized when trying to install Prime NG that Angular 2.0.0-beta.15 wants zone.js 0.6.10.  Can you update package.json from 0.6.6 to 0.6.10 for primeng?

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "primeng"
npm ERR! node v4.4.1
npm ERR! npm  v2.14.20
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package zone.js@0.6.10 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular2@2.0.0-beta.15 wants zone.js@^0.6.10
npm ERR! peerinvalid Peer primeng@1.0.0-beta.2 wants zone.js@0.6.6

**Comment by cagataycivici** [comment]
Fixed now, as beta.3 only requires angular2 and primeui.
