### ISSUE TITLE
No value accessor for '' using quickstart and prime-slider

### ISSUE THREAD

**Issue by goleary** [primefaces/primeng-quickstart#4]
I started with this quickstart and added a slider to the app.component

    import {Component} from 'angular2/core';
    import {InputText, Slider} from 'primeng/primeng';

    @Component({
	selector: 'my-app',
	template: `
        <h1>My First 2 App</h1>
        <input type="text" pInputText [(ngModel)]="text" />
        {{text}}
        <p-slider [(ngModel)]="val"></p-slider>
        {{val}}
      `,
      directives: [InputText]
    })
    export class AppComponent {
    val: number;
    text: string;
    }

but I get the error mentioned in the title

**Comment by cagataycivici** [comment]
I think directives should be;

```ts
directives: [InputText,Slider]
```

**Comment by DanielleJobeJKI** [comment]
I am seeing the same error and am doing the same as above, but without the InputText component, and am including Slider in the directives.
